name: Build and Deploy Next.js Docker to Home Server

on:
  push:
    branches:
      - main # หรือ branch ที่คุณต้องการ Deploy

env:
  REGISTRY: ghcr.io # GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }} # ชื่อ Image จะเป็น username/repository_name

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read # สิทธิ์ในการอ่าน repository (สำหรับ checkout)
      packages: write # สิทธิ์ในการเขียนไปยัง GitHub Packages (GHCR)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # User ที่ทริกเกอร์ Workflow
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN มีสิทธิ์ push ไปยัง GHCR ใน repo เดียวกัน

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: | # สร้าง Tags สำหรับ Image
            type=sha # Tag ด้วย commit SHA
            type=raw,value=latest,enable={{is_default_branch}} # Tag 'latest' ถ้าเป็น default branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path ไปยัง Dockerfile (Root ของ Repo)
          push: true # Push Image ไปยัง Registry
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # ใช้ GitHub Actions cache สำหรับ Docker layer caching
          cache-to: type=gha,mode=max

  deploy-to-server:
    name: Deploy Docker Container to Server
    needs: build-and-push-docker-image # Job นี้จะรันหลังจาก build-and-push-docker-image สำเร็จ
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.

            IMAGE_TAG="sha-${GITHUB_SHA::7}" # ใช้ Commit SHA แบบสั้นเป็น Tag (หรือ 'latest')
            FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG"
            # ถ้าคุณใช้ tag 'latest' ให้เปลี่ยน IMAGE_TAG เป็น "latest"
            # FULL_IMAGE_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

            CONTAINER_NAME="my-nextjs-app" # ตั้งชื่อ Container ของคุณ

            echo "🐳 Logging in to GitHub Container Registry on server..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

            echo "🚚 Pulling Docker image: $FULL_IMAGE_NAME"
            docker pull $FULL_IMAGE_NAME

            echo "🛑 Stopping and removing old container (if exists)..."
            docker stop $CONTAINER_NAME || true # || true เพื่อไม่ให้ error ถ้า container ไม่มีอยู่
            docker rm $CONTAINER_NAME || true

            echo "🚀 Running new Docker container..."
            docker run -d \
              -p 3000:3000 \
              --name $CONTAINER_NAME \
              --restart always \
              # (Optional) -v /path/on/server/persistent-data:/app/data \ # Mount volume ถ้าต้องการ
              # (Optional) -e MY_ENV_VAR="some_value" \ # ส่ง Environment Variables
              $FULL_IMAGE_NAME

            echo "🧹 Cleaning up old images (optional)..."
            docker image prune -f

            echo "🎉 Deployment to home server completed successfully!"
